site_name: "David's Notes"

docs_dir: docs/

# Theme
theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/library
  features:
    - navigation.tabs
    - navigation.instant
    # - navigation.expand
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy

# nav:
#  - Home: 'index.md'
#  - Projects: 'Projects.md'
#  - Notes: 'Notes.md'

# Extensions
markdown_extensions:
  - footnotes
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - nl2br
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  - toc:
      permalink: true

plugins:
  - search
  - roamlinks 
  - mermaid2
  - callouts

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 
